version: '3.9'

services:
  postgres:
    image: postgres
    volumes:
      - ./data/postgres:/data/postgres
    ports:
      - 5342:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=exa-candidate
    restart: unless-stopped

  api:
    build:
      context: .
    ports:
      - 3000:3000
    restart: always
    volumes:
      - ./:/opt/app
    depends_on:
      - postgres
