version: '3.9'

services:
  postgres:
    image: postgres:alpine
    volumes:
      - ./data/postgres:/data/postgres
    ports:
      - 5342:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres