@startuml

class Task {
    String title
    String description
    Date dueDate
    Date createdAt
    Date updatedAt
    Date doneAt
    TaskStatus status
}

enum TaskStatus {
    PENDING
    COMPLETED
}

@enduml